SpaceBlackMarketMVC/Controllers/ItemController.cs
using Microsoft.AspNet.Identity;
using SpaceBlackMarket.Models.ItemModels;
using SpaceBlackMarket.Services;
using SpaceBlackMarketMVC.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SpaceBlackMarketMVC.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult Index()
        {
            //var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ItemService();
            var model = service.GetItems();
            return View(model);
        }
        
        // GET
        public ActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateItemService();

            if (service.CreateItem(model))
            {
                TempData["SaveResult"] = "Your item was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Item could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateItemService();
            var model = svc.GetItemById(id);

            return View(model);
        }

        private ItemService CreateItemService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ItemService();
            return service;
        }

        public ActionResult Edit(int id)
        {
            var service = new ItemService();
            var detail = service.GetItemById(id);
            var model =
                new ItemEdit
                {
                    ItemId = detail.ItemId,
                    ItemName = detail.ItemName,
                    ItemPrice = detail.ItemPrice,
                    ItemDescription = detail.ItemDescription,
                    ItemType = detail.ItemType,
                    SmuggleDelivery = detail.SmuggleDelivery
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ItemEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.ItemId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateItemService();

            if (service.UpdateItem(model))
            {
                TempData["SaveResult"] = "Your Item was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your item could not be updated.");
            return View();
        }

        public ActionResult Delete(int id)
        {
            var svc = CreateItemService();
            var model = svc.GetItemById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateItemService();

            service.DeleteItem(id);

            TempData["SaveResult"] = "Your Item was deleted.";

            return RedirectToAction("Index");
        }
    }
}

SpaceBlackMarketMVC/Controllers/OutpostController.cs
using SpaceBlackMarket.Models.OutpostModels;
using SpaceBlackMarket.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpaceBlackMarketMVC.Controllers
{
    
    public class OutpostController : Controller
    {
        [Authorize]
        // GET: Outpost
        public ActionResult Index()
        {
            var service = new OutpostService();
            var model = service.GetOutposts();
            return View(model);
        }

        // GET
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin, User")]
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OutpostCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = new OutpostService();

            if (service.CreateOutpost(model))
            {
                TempData["SaveResult"] = "Outpost Created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Outpost could not be created.");

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = new OutpostService();
            var model = svc.GetOutpostById(id);

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = new OutpostService();
            var detail = service.GetOutpostById(id);
            var model =
                new OutpostEdit
                {
                    OutpostId = detail.OutpostId,
                    OutpostName = detail.OutpostName,
                    GalaxyName = detail.GalaxyName,
                    PlanetName = detail.PlanetName,
                    DangerLevel = detail.DangerLevel
                };
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OutpostEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.OutpostId != id)
            {
                ModelState.AddModelError("", "Id does not match.");
                return View(model);
            }

            var service = new OutpostService();

            if (service.UpdateOutpost(model))
            {
                TempData["SaveResult"] = "Outpost has been updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Outpost could not be updated.");
            return View();
        }

        [Authorize(Roles = "Admin")]
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = new OutpostService();
            var model = svc.GetOutpostById(id);

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = new OutpostService();

            service.DeleteOutpost(id);

            TempData["SaveResult"] = "Outpost Deleted.";

            return RedirectToAction("Index");
        }

    }
}

SpaceBlackMarketMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Space Black Market</title>
    <link rel="icon" href="~/icon.ico.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body class="d-flex flex-column min-vh-100">
    @if (Request.IsAuthenticated)
    {
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/Content/Image/astronaut.png" id="astro" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Menu
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li class="dropdown-item"> @Html.ActionLink("Home", "Index", "Home")</li>
                                <li class="dropdown-item"> @Html.ActionLink("Outposts", "Index", "Outpost")</li>
                                <li class="dropdown-item"> @Html.ActionLink("Roles", "Index", "Roles")</li>
                                <li class="dropdown-item"> @Html.ActionLink("The Market", "Index", "Item")</li>
                                <li class="dropdown-item"> @Html.ActionLink("About Us", "About", "Home")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            @Html.Partial("_LoginPartial")
        </nav>

    }

    <br />

    <div class="container body-content">
        @RenderBody()
    </div>


    <div>
        <footer class="footer fixed-bottom">
            <p>&copy; @DateTime.Now.Year - This isn't a black market</p>
        </footer>
    </div>
    <style>

        footer {
            text-align: center;
        }

        #navbarDarkDropdownMenuLink {
            background-color: black;
        }

        #navbarDarkDropdownMenuLink:hover {
            background-color: #bdbcbc;
            color: black;
        }

        .dropdown-item {
            padding: 5px;
            text-align: center;
            transition: transform 0.4s;
        }

        .navbar {
            background-image: url(/Content/Image/MilkyWayNav.jpg)
        }

        body {
            height: 100vh;
        }

        a {
            text-decoration: none;
            color: white;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        }

            a:hover {
                color: white;
            }

        .nav-item {
            text-decoration: none !important;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: transparent;
        }


        #astro {
            height: 50px;
            width: 50px;
            transition: transform .4s;
            top: 0;
            position: relative;
        }

            #astro:hover {
                transform: scale(1.2);
            }
    </style>



    @RenderSection("scripts", required: false)

</body>
</html>